version: "3.9"

services:
  dev:
    container_name: e-commerce-config-server
    build: .
    ports:
      - "8085:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    environment:
      SPRING_APPLICATION_NAME: e-commerce-config-server
      SPRING_PROFILES_ACTIVE: dev
